### ISSUE TITLE
Slow scrolling with NERDTree open.

### ISSUE THREAD

**Issue by BasketaksSjargong** [scrooloose/nerdtree#401] opened 2014-11-17 08:23 UTC
I've noticed recently that scrolling in a buffer is noticeably slower with NERDTree toggled on than with NERDTree toggled off. I couldn't find any open issues that adressed this.

I tried running Vim with NERDTree as the only plugin, and the same occured.

**Comment by yoshuawuyts** [comment] 2015-01-22 16:01
Found this to also be the case. Kind of annoying; coming from IDE's (atom, sublime) I like to have my dir tree open.

**Comment by SweetAndLow** [comment] 2015-01-27 18:40
I'm having similar symptoms. Opening a python file with ~200 lines and scrolling is very slow. I turned off all other plugins and isolated it to be nerd tree causing the issues.

**Comment by kjanssen** [comment] 2015-03-02 02:21
Glad I discovered this issue. I've been trying to figure out what is bogging up my Vim rendering for a while now, and I realized it only happens when NERDTree is open. It seems to happen worst when scrolling through sections of long lines. That is, when there are a lot of total characters being rendered at once.

I'll admit, I probably shouldn't rely so much on having NERDTree open all the time, but it's really nice when I'm in a project with a lot of files in a lot of directories. At least now I'll remind myself to close it when I'm not actually using it.

**Comment by kuzzmi** [comment] 2015-04-07 13:54
Very annoying, agree. 
But I found that the problem exists when the buffer which is scrolled has a highlighted syntax. 'Cause I've tried to disable it and everything worked well.

**Comment by mantiz** [comment] 2015-04-15 12:27
Same here. But disabling syntax highlightning doesn't change a thing for me.
I have not tried to disable any other plugin since simply hiding the NERDTree makes scrolling flawless.

**Comment by mantiz** [comment] 2015-04-15 17:25
Nevermind, I think the problem is not specific to NERDTree, at least for me.
I tried to observe the behaviour a bit and finally found that vertically split windows are causing slow scrolling speed for me. Everything seems fine if two windows are split horizontally but if I change to vertically split windows (like it is also the case with NERDTree open) it gets laggy.
If I open just one file plus NERDTree and change the layout to horizontal split, the scrolling is also fast.

**Comment by dragonxlwang** [comment] 2016-03-29 03:04
Sorry to pick up this thread again and I agree with @mantiz. I think it actually has something to do with multiple panes (esp. vertical split). And this only occurs when using a large monitor and have the terminal (for me iterm2) spanning over the screen. (I'm using macvim in iterm2 to show the below screencast)

My only solution is to use gui macvim which seems to use a much better rendering than terminal macvim. However, I hope to went back everything in iterm2 again. Let me know if you have any solutions.

![untitled](https://cloud.githubusercontent.com/assets/15812510/14096779/e966a700-f530-11e5-82da-cef61431d813.gif)

**Comment by Ilyes512** [comment] 2016-09-16 22:31
Wow, I was getting annoyed by the slow scrolling and I also thought it was nerdtree at first. I can confirm it's tmux. I also found this: http://unix.stackexchange.com/questions/49414/tmux-output-is-slower-when-vertical-splits-exist-why

**Comment by pencilcheck** [comment] 2017-08-18 03:26
Yea, it start really slow especially after opening folder with a lot of items in it, and persists even after closing the folder. The workaround mentioned in the link above doesn't really help solve it. For now what we should we do to fix this? because netrw doesn't have this issue in tmux.

**Comment by PhilRunninger** [comment] 2018-08-07 20:42
There's really nothing that can be done in NERDTree to fix this. As discovered above, there are a number of other factors at play here, from syntax highlighting (some languages are slower than others, especially on long lines of code) to vertical splits to tmux.

**Closed by PhilRunninger** 2018-08-07 20:42 UTC

**Comment by bechampion** [comment] 2020-12-22 11:32
devicons was my culprit

**Comment by PhantomCloak** [comment] 2022-08-15 23:05
cause was the devicons for me, apparently I didn't find another solution than deleting 

NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local
