### ISSUE TITLE
[API-HOW-TO] Create/Open file

### ISSUE THREAD

**Issue by cabaalexander** [scrooloose/nerdtree#995] opened 2019-05-17 13:58 UTC
Hi,

The other day I created a plugin for creating a script file in your current selected node. Right now my plugin just creates the script with executable permissions and refresh nerdtree.

I want to know how is the right way to open it in a new buffer, I want it to work like a preview or to edit it right away. 

Yesterday I did try with the `Opener` object and then tried to instanciate an `NERDTreeFileNode` and open it, no luck with that either.

Here's the link to my plugin:

https://github.com/cabaalexander/nerdtree-doscript

Any suggestion is welcome.

(I couldn't provide visual examples 'cause I'm on my phone)

**Comment by PhilRunninger** [comment] 2019-06-19 03:37
Try these commands, adapting them as necessary. They use your `path` and `scriptName` variables.

```vim
let pathObj = g:NERDTreePath.New(path . '/' . scriptName)
let node = g:NERDTreeFileNode.New(pathObj, b:NERDTree)
call node.open()
```

Or, if you know the cursor is on the file you want to open,...

```vim
let node=g:NERDTreeFileNode.GetSelected()
call node.open()
```

**Comment by PhilRunninger** [comment] 2019-06-19 03:39
Closing this, since it's not a bug report or feature request. Comments can still be added to it after closing.

**Closed by PhilRunninger** 2019-06-19 03:39 UTC
