### ISSUE TITLE
Error when invoking nerdtree - E488 trailing characters

### ISSUE THREAD

**Issue by smenzer** [scrooloose/nerdtree#508] opened 2015-11-20 16:50 UTC
## Overview
I am installing fresh on a new machine and ran into an error when invoking Nerdtree in vim.  I think it's related to 5.0 because I had another machine that had an older version working fine, but when I upgraded Nerdtree I hit the same error.  Details about the error and my environment below, but let me know if you need anything else to troubleshoot.

## Error
When I use my keyboard shortcut to invoke nerdtree, I get the following error:
```
Error detected while processing function 197..198..181..123:
line 14:
E488: Trailing characters
Press ENTER or type command to continue
```
When I hit ENTER, I am able to see the nerdtree and browse around.  Anytime I hit enter to open a directory, I get another, similar, error:
```
Error detected while processing function nerdtree#ui_glue#invokeKeyMap..74..73..<SNR>32_activateDirNode..130..123:
line 14:
E488: Trailing characters
Press ENTER or type command to continue
```

## Environment
VIM version 7.3
OSX version 10.11.1

**Comment by scrooloose** [comment] 2015-11-20 17:05
I'm trying to reproduce this - can you show me any nerdtree settings in your vimrc?

Would be useful if we knew exactly what function was failing :-/ Goddamn vim and its awesome debugging output.

**Comment by smenzer** [comment] 2015-11-20 17:38
I load the plugin using vundle:
```
Plugin 'scrooloose/nerdtree'
```

And the only other setting I have in my .vimrc related to nerdtree is this:
```
"** Nerdtree **
let NERDTreeQuitOnOpen=1
map <C-c> :NERDTreeToggle<CR>
```

**Comment by scrooloose** [comment] 2015-11-20 18:42
OK, I'm faaairly certain that it's this line: 

https://github.com/scrooloose/nerdtree/blob/master/lib/nerdtree/tree_file_node.vim#L291

Can you comment it out and see if the error persists?

If the error disappears, then I'm guessing your version of vim doesn't like `obj.method().anotherMethod()` syntax (i.e. the chaining) - vim has historically had issues with this sort of stuff.

Let me know how it goes :)

**Comment by jayunit100** [comment] 2015-11-20 18:47
Commenting the render line 291 above indeed
fixes the error message.


BUT folders still don't expand ....

**Comment by smenzer** [comment] 2015-11-20 18:56
Commenting line 291 worked for me - it fixed the error message AND folders are expanding for me.

**Comment by scrooloose** [comment] 2015-11-20 19:18
OK - I have pushed a fix. @jayunit100 what version of vim are you running?

I'm somewhat torn about what to do in future... since not having method chaining is a PITA. NERDTree may end up requiring vim7.4+ in future - which doesn't seem to insane since it is over 2 years old now.

Anyway, let me know if there are any issues :)

**Closed by scrooloose** 2015-11-20 19:18 UTC

**Comment by SubhashShah-BTC** [comment] 2016-05-19 05:41
I am facing this problem on "NERDTreeFind".

**Comment by lumen82** [comment] 2018-10-27 05:15
Everytime I open a node ,this happen
vim 8.1

**Comment by PhilRunninger** [comment] 2018-10-27 13:45
@lumen82 , Could you create a new issue for the behavior you're observing? A lot has changed since this one was opened and closed. Please provide as much information as possible so I can recreate the issue.
