### ISSUE TITLE
Pressing 'i' splits in the nerdtree browser when nerdtree is started from autocmd

### ISSUE THREAD

**Issue by joslinm** [scrooloose/nerdtree#438] opened 2015-04-22 14:58 UTC
I stuck this in my vimrc: `autocmd vimenter * NERDTree`

I then started vim in a directory by doing `vim .` and in the main window, browsed to a file. 

Then I intended to split horizontally another file so I went to nerdtree browser and pressed 'i' on a file. It split it in the nerdtree browser

**Comment by scrooloose** [comment] 2015-05-06 20:33
I am unable to reproduce this. Can you show me your vimrc?

**Comment by PhilRunninger** [comment] 2018-01-01 20:53
I can't reproduce this either. With no feedback in over 2 years, I'm going to close this. Reopen if necessary.

**Closed by PhilRunninger** 2018-01-01 20:53 UTC
