### ISSUE TITLE
Cannot open file or directory whose name include [ or ]

### ISSUE THREAD

**Issue by faaaar** [scrooloose/nerdtree#680] opened 2017-04-04 12:41 UTC
MacOS 10.12.3
Vim 8.0
scrooloose/nerdtree installed via vundle

**Comment by lifecrisis** [comment] 2017-06-23 01:03
Confirmed this bug on my installations.

**Comment by PhilRunninger** [comment] 2017-06-24 04:29
I believe this is only a problem when the file contains both brackets, with [ followed by ]. I'm not even seeing the file in the NERDTree. #391 may be the same issue.

**Comment by lifecrisis** [comment] 2017-06-24 13:35
Hey, @PhilRunninger! I've isolated the bug to the `s:UI._stripMarkup()` in `ui.vim`. It was pretty clear that files like this must be treated like flags, so I looked there. I'm fairly confident that [line 389](https://github.com/scrooloose/nerdtree/blob/master/lib/nerdtree/ui.vim#L389) in `ui.vim` is the source of our problem.

I'm not a regular expression wizard yet. Maybe you can take a look.

**Comment by PhilRunninger** [comment] 2017-06-26 12:45
It looks like [line 389](https://github.com/scrooloose/nerdtree/blob/master/lib/nerdtree/ui.vim#L389) is used to remove the flag that git-nerdtree-plugin puts on, but if **`foo[bar].txt`** is not a git-controlled file, it removes the wrong thing. If we force **`substitute()`** to look at the beginning of the word only, then we run into problems with **`[foo]bar.txt`**. My initial thought was to use **`filereadable()`**, and skip the substitute if it's not needed.

**Comment by lifecrisis** [comment] 2017-06-26 12:49
That actually sounds like a good decision for now. It seems more like a temporary fix, because other flags can exist that cause `filereadable()` to fail. We might need a more "heavyweight" solution for a long-term fix.

**Comment by xcambar** [comment] 2018-02-14 11:14
I've been hit with this bug and even though I agree that the problem requires a significant change to be rock-solid, but I've found a minimal change that works under the (weak) assumption that flags **generally** use special characters.

Here's the patch, for those interested:

```patch
diff --git a/lib/nerdtree/ui.vim b/lib/nerdtree/ui.vim
index 196d745..07a87e6 100644
--- a/lib/nerdtree/ui.vim
+++ b/lib/nerdtree/ui.vim
@@ -381,7 +381,7 @@ function! s:UI._stripMarkup(line)
     let line = substitute (line, '*\ze\($\| \)', "","")
 
     " strip off any generic flags
-    let line = substitute (line, '\[[^]]*\]', "","")
+    let line = substitute (line, '\[\W*\]', "","")
 
     let line = substitute (line,' -> .*',"","") " remove link to
 
```

Should you be interested in a PR, I'm just a ping away :)

**Comment by PhilRunninger** [comment] 2018-06-29 21:33
@lifecrisis, I'm thinking about a fix for this issue. What if we used a non-breaking space (ASCII code 160) to delimit the filename from the flags and bookmark label? That character is very unlikely to be used in a filename, and parsing the node's text would be a lot easier. I'll work on it, and throw a PR out for review.

**Comment by PhilRunninger** [comment] 2018-08-17 11:57
@faaaar @xcambar , would you be willing to test the pull request #868 I've put together for this issue? Details are in the PR. Thanks.

**Comment by xcambar** [comment] 2018-08-20 11:34
I confirm #868 fixes the issue. Congrats and thanks!

**Comment by faaaar** [comment] 2018-08-21 06:57
#868 fixes the issue. thanks!

**Comment by PhilRunninger** [comment] 2018-08-21 09:52
Thanks for confirming this for me. I'll close the issue again when I do the merge.

**Closed** 2018-10-25 02:41 UTC
Labels: PR Under Review, bug, nodes with bad characters
