### ISSUE TITLE
can not create `.gcmrc` file

### ISSUE THREAD

**Issue by itsNikolay** [scrooloose/nerdtree#463] opened 2015-07-03 21:42 UTC
`NERDTree: Node Not Created.`
![screenshot at 00-41-07](https://cloud.githubusercontent.com/assets/786577/8505055/662673da-21e5-11e5-93f1-e87f382b1d65.png)

**Comment by Delapouite** [comment] 2015-07-07 07:07
You may have tried to create an already existing .gcmrc file? Did you enable invisible files in your tree?

**Comment by PhilRunninger** [comment] 2018-01-02 14:38
@itsNikolay, I can't test this on Windows right now, and I suspect that is where you're running vim. Windows doesn't like Unix-like hidden files, but there is a trick. Use the filename `.gcmrc.`. The trailing period tells Windows that there is no extension, and it will create the file with the name you intended.

If you're on a Mac/*nix system, then I'll need more information to diagnose.

**Comment by lifecrisis** [comment] 2018-04-29 13:50
Not enough information has been provided here. I have tested this on Windows and I cannot replicate the given error message.  I will now close this issue... reopen if you can supply a clear and precise procedure for reproducing your problem.  Thanks!

**Closed by lifecrisis** 2018-04-29 13:50 UTC
