### ISSUE TITLE
Vim hangs with custom statusline in Windows

### ISSUE THREAD

**Issue by yous** [scrooloose/nerdtree#467] opened 2015-07-17 15:24 UTC
See itchyny/lightline.vim#121. I configured lightline.vim with:

``` vim
let g:lightline = {
      \ 'component_function': {
      \   'filename': 'LightLineFilename' } }

function! LightLineFilename()
  let fname = expand('%:t')
  return fname == '__Tag_List__' ? '' :
        \ fname == 'ControlP' ? '' :
        \ fname =~ 'NERD_tree' ?
        \   (exists('g:NERDTreeFileNode') &&
        \     has_key(g:NERDTreeFileNode.GetSelected(), 'path') ?
        \     g:NERDTreeFileNode.GetSelected().path.getLastPathComponent(0) :
        \     '') :
        \ '' != fname ? fname : '[No Name]'
endfunction
```

Then statusline of NERDTree shows filename of the file node which cursor points to. But when I open gVim in `C:\Users\<USER>`, it hangs and I can't interact.

![screenshot 2015-07-17 22 53 46](https://cloud.githubusercontent.com/assets/853977/8748618/b6ba5b62-2cd6-11e5-9f33-1dafeec6ae33.png)

If I use empty statusline, then NERDTree opens with an error message `NERDTree: 3 file(s) could not be loaded into the NERD tree`. Also, if I open NERDTree on other directories and then change directory of it to the `C:\Users\<USER>`, there is no such problem.

I executed `:debug NERDTree` and it seems to stuck in `redraw` command on [`call nerdtree#echoWarning`](https://github.com/scrooloose/nerdtree/blob/10261d60a05c3a2237a2b5e47df9235d52430e57/lib/nerdtree/tree_dir_node.vim#L273). How can I look into this problem?

**Comment by yous** [comment] 2015-07-18 07:13
Also this problem is reproducible without using lightline.vim. This is a minimal vimrc:

``` vim
set nocompatible
filetype off
call plug#begin()
" Enable NERDTree
Plug 'scrooloose/nerdtree'
call plug#end()
filetype plugin indent on
syntax on

let g:NERDTreeStatusline = "%{exists('g:NERDTreeFileNode')&&" .
      \ "has_key(g:NERDTreeFileNode.GetSelected(),'path')?" .
      \ "g:NERDTreeFileNode.GetSelected().path.getLastPathComponent(0):''}"
```

Is it bug of NERDTree, or is it wrong using some NERDTree functions inside the statusline of NERDTree? Maybe I should find some workarounds.

**Comment by PhilRunninger** [comment] 2018-03-15 12:51
@yous, I've been going through the backlog of issues. I cannot reproduce this issue, and it's possible a fix was introduced since you raised the issue. Can you provide more information about this, or close the issue?

**Comment by yous** [comment] 2018-03-16 03:46
Hi, @PhilRunninger. This issue is quite old, and I'm not using NERDTree now, so it would take some time to reproduce this. If this was fixed by recent updates, I'll close this.

**Comment by yous** [comment] 2018-03-16 11:34
Hi, I can tell this is still reproducible with Windows gVim and Vim.

1. Make a file with above minimal vimrc (e.g. `tmp.vimrc`)
2. Open Vim with `tmp.vimrc` (`gvim.exe -u tmp.vimrc` or `vim.exe -u tmp.vimrc`)
3. Run `:NERDTree`

Then Vim freezes until I press Ctrl-C, and after I press it, Vim doesn't accept inputs.
I used official gVim release:

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 23 2017 20:01:28)
MS-Windows 32-bit GUI version with OLE support
Included patches: 1-586
Compiled by mool@tororo
Huge version with GUI.  Features included (+) or not (-):
+acl                +comments           +ex_extra           +keymap             +multi_byte_ime/dyn +python3/dyn        -tag_any_white      +viminfo
+arabic             +conceal            +extra_search       +lambda             +multi_lang         +quickfix           +tcl/dyn            +vreplace
+autocmd            +cryptv             +farsi              +langmap            -mzscheme           +reltime            -termguicolors      +wildignore
+balloon_eval       +cscope             +file_in_path       +libcall            +netbeans_intg      +rightleft          -tgetent            +wildmenu
+browse             +cursorbind         +find_in_path       +linebreak          +num64              +ruby/dyn           -termresponse       +windows
++builtin_terms     +cursorshape        +float              +lispindent         +ole                +scrollbind         +textobjects        +writebackup
+byte_offset        +dialog_con_gui     +folding            +listcmds           +packages           +signs              +timers             -xfontset
+channel            +diff               -footer             +localmap           +path_extra         +smartindent        +title              -xim
+cindent            +digraphs           +gettext/dyn        -lua                +perl/dyn           +startuptime        +toolbar            +xpm_w32
+clientserver       +directx            -hangul_input       +menu               +persistent_undo    +statusline         +user_commands      -xterm_save
+clipboard          -dnd                +iconv/dyn          +mksession          -postscript         -sun_workshop       +vertsplit          
+cmdline_compl      -ebcdic             +insert_expand      +modify_fname       +printer            +syntax             +virtualedit        
+cmdline_hist       +emacs_tags         +job                +mouse              +profile            +tag_binary         +visual             
+cmdline_info       +eval               +jumplist           +mouseshape         +python/dyn         +tag_old_static     +visualextra        
   system vimrc file: "$VIM\vimrc"
     user vimrc file: "$HOME\_vimrc"
 2nd user vimrc file: "$HOME\vimfiles\vimrc"
 3rd user vimrc file: "$VIM\_vimrc"
      user exrc file: "$HOME\_exrc"
  2nd user exrc file: "$VIM\_exrc"
  system gvimrc file: "$VIM\gvimrc"
    user gvimrc file: "$HOME\_gvimrc"
2nd user gvimrc file: "$HOME\vimfiles\gvimrc"
3rd user gvimrc file: "$VIM\_gvimrc"
       defaults file: "$VIMRUNTIME\defaults.vim"
    system menu file: "$VIMRUNTIME\menu.vim"
Compilation: cl -c /W3 /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32  -DFEAT_CSCOPE -DFEAT_NETBEANS_INTG -DFEAT_JOB_CHANNEL   -DFEAT_XPM_W32   -DWINVER=0x0501 -D_WIN32_WINNT=0x0501  /Fo.\ObjGXOLYHTRi386/ /Ox /GL -DNDEBUG  /Zl /MT -DFEAT_OLE -DFEAT_MBYTE_IME -DDYNAMIC_IME -DFEAT_GUI_W32 -DFEAT_DIRECTX -DDYNAMIC_DIRECTX -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_TCL -DDYNAMIC_TCL -DDYNAMIC_TCL_DLL=\"tcl86.dll\" -DDYNAMIC_TCL_VER=\"8.6\" -DFEAT_PYTHON -DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL=\"python35.dll\" -DFEAT_PERL -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DDYNAMIC_PERL -DDYNAMIC_PERL_DLL=\"perl524.dll\" -DFEAT_RUBY -DDYNAMIC_RUBY -DDYNAMIC_RUBY_VER=22 -DDYNAMIC_RUBY_DLL=\"msvcrt-ruby220.dll\" -DFEAT_HUGE /Fd.\ObjGXOLYHTRi386/ /Zi
Linking: link /RELEASE /nologo /subsystem:windows /LTCG:STATUS oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib uuid.lib /machine:i386 gdi32.lib version.lib   winspool.lib comctl32.lib advapi32.lib shell32.lib  /machine:i386 /nodefaultlib libcmt.lib oleaut32.lib user32.lib     /nodefaultlib:python27.lib /nodefaultlib:python35.lib   "E:\tcl\lib\tclstub86.lib" WSock32.lib xpm\x86\lib\libXpm.lib /PDB:gvim.pdb -debug
```

**Comment by PhilRunninger** [comment] 2018-03-16 12:51
Ah, Windows! I was testing it on my Mac. I'll look at it later on my Windows machine.

**Closed** 2019-07-04 04:21 UTC
Labels: close?
