### ISSUE TITLE
Getting the following errors when renaming from NERDTree menu

### ISSUE THREAD

**Issue by npearson72** [scrooloose/nerdtree#374] opened 2014-08-23 01:40 UTC
Error detected while processing function nerdtree#ui_glue#invokeKeyMap..80..79..<SNR>44_showMenu..54..71..NERDTreeMoveNode..132..43..107:
line   12:
E482: Can't create file <empty>
Error detected while processing function nerdtree#ui_glue#invokeKeyMap..80..79..<SNR>44_showMenu..54..71:
line    6:
E171: Missing :endif
Error detected while processing function nerdtree#ui_glue#invokeKeyMap..80..79..<SNR>44_showMenu..54:
line   19:
E171: Missing :endif
Error detected while processing function nerdtree#ui_glue#invokeKeyMap..80..79:
line    3:
E171: Missing :endif
Error detected while processing function nerdtree#ui_glue#invokeKeyMap..80:
line   33:
E171: Missing :endif
Press ENTER or type command to continue

**Comment by soyuka** [comment] 2015-01-16 09:07
Setting
```
let g:NERDTreeBookmarksFile = $HOME ."/.vim/bundle/nerdtree/bookmarks" #existing path to bookmarg
```
Fixed my issue.

**Comment by 10p10110111xxi11p00100100** [comment] 2015-01-16 15:23
I think the newest version of NERDTree fixed this issue on Windows 7. My bookmarks work as intended as well, without any special modifications to _vimrc .

**Comment by thiagoserra** [comment] 2016-10-04 14:18
I'm getting this kind of error when I try use "OpenBookmark name".
File Bookmark is ok com my user profile on Windows 10.


![erro](https://cloud.githubusercontent.com/assets/3385403/19077722/10612cd0-8a24-11e6-91ea-0da8bea3a39c.png)

**Comment by PhilRunninger** [comment] 2018-04-10 21:46
I'm closing this because of the age of the issue. Try again with the latest version of NERDTree, and reopen if necessary.

**Closed by PhilRunninger** 2018-04-10 21:46 UTC
