### ISSUE TITLE
Error detected while processing function nerdtree#ui_glue#invokeKeyMap

### ISSUE THREAD

**Issue by aliev** [scrooloose/nerdtree#752] opened 2017-10-27 19:40 UTC
When I'm trying to open directory:

```
Error detected while processing function nerdtree#ui_glue#invokeKeyMap[1]..74[26]..73[3]..<SNR>37_activateDirNode[1]..130[3]..228[1]..249[36]..127[1]..128[26]..128[26]..128[26]..128:
line   10:
E315: ml_get: invalid lnum: 27
```

OSX High Sierra

My Vimrc: https://github.com/aliev/vim/blob/master/vimrc

NERDTree:
```
git rev-parse --short HEAD
8a6ae7c
```

vim --version
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct 17 2017 11:22:06)
MacOS X (unix) version
Included patches: 1-1200
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     -tcl
-balloon_eval    +folding         +mouse_xterm     +termguicolors
-browse          -footer          +multi_byte      +terminal
++builtin_terms  +fork()          +multi_lang      +terminfo
+byte_offset     -gettext         -mzscheme        +termresponse
+channel         -hangul_input    +netbeans_intg   +textobjects
+cindent         +iconv           +num64           +timers
-clientserver    +insert_expand   +packages        +title
+clipboard       +job             +path_extra      -toolbar
+cmdline_compl   +jumplist        +perl            +user_commands
+cmdline_hist    +keymap          +persistent_undo +vertsplit
+cmdline_info    +lambda          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      +startuptime     -xpm
+eval            +mouse_dec       +statusline      -xsmp
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_clipboard
+extra_search    -mouse_jsbterm   +syntax          -xterm_save
+farsi           +mouse_netterm   +tag_binary      
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -framework Cocoa   -mmacosx-version-min=10.13 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.26.1/lib/perl5/5.26.1/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc -F/usr/local/opt/python/Frameworks -framework Python   -lruby.2.4.2 -lobjc
```

**Comment by PhilRunninger** [comment] 2018-05-09 14:11
@aliev, There is not much information to go on here. Could you detail the steps and your environment a bit more, or let us know how you solved the issue? 'E315` is an internal Vim error, and there need to be reproducible steps in order to find the root cause of the error.

**Comment by AnthonyWharton** [comment] 2018-10-31 15:14
Hi there,

I've also experienced a similar error after the automatic reloading of files when renaming files in nerdtree. It may or may not be related, but I'm happy to offer information if you ask me what you need! 😃 

Error:
```
Error detected while processing function nerdtree#ui_glue#invokeKeyMap[1]..76[33]..75[3]..<SNR>30_showMenu[2]..49[25]..66[6]..NERDTreeMoveNode[23]..<SNR>32_promptToRenameBuffer:
line   15:
E517: No buffers were wiped out: bwipeout! 131
Error detected while processing function nerdtree#ui_glue#invokeKeyMap[1]..76[33]..75[3]..<SNR>30_showMenu[2]..49[25]..66:
line    6:
E171: Missing :endif
Error detected while processing function nerdtree#ui_glue#invokeKeyMap[1]..76[33]..75[3]..<SNR>30_showMenu[2]..49:
line   25:
E171: Missing :endif
Error detected while processing function nerdtree#ui_glue#invokeKeyMap[1]..76[33]..75:
line    3:
E171: Missing :endif
Error detected while processing function nerdtree#ui_glue#invokeKeyMap[1]..76:
line   33:
E171: Missing :endif
```

I've installed NerdTree through plug and have made sure it's clean and up to date.

*Hopefully* all the `.vimrc` settings related to NerdTree:
```
" Tree
let NERDTreeMinimalUI  = 1
let NERDTreeDirArrows  = 1
let NERDTreeShowHidden = 1
let g:NERDTreeWinSize  = 36
nmap <silent> <A-Up>    :wincmd k<CR>
nmap <silent> <A-Down>  :wincmd j<CR>
nmap <silent> <A-Left>  :wincmd h<CR>
nmap <silent> <A-Right> :wincmd l<CR>
nmap <silent> <A-k>     :wincmd k<CR>
nmap <silent> <A-j>     :wincmd j<CR>
nmap <silent> <A-h>     :wincmd h<CR>
nmap <silent> <A-l>     :wincmd l<CR>
map  <C-\>              :NERDTreeToggle<CR>
autocmd VimEnter * NERDTree  " Autostart NERDTree
autocmd VimEnter * wincmd p  " And then focus on file
autocmd BufWinEnter * NERDTreeMirror
autocmd BufEnter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
```

**Comment by PhilRunninger** [comment] 2018-10-31 18:09
@AnthonyWharton, it appears you aren't running an up-to-date version of NERDTree. (The `promptToRenameBuffer` function has been refactored out of the code.) There was an update to this file committed 7 days ago. Update NERDTree, and if the issue persists, answer these questions, so it can be diagnosed. 

1. If you were renaming a file, was it open in NERDTree?
1. If you were renaming a directory, were there files under it open in NERDtree?
1. If this is a repeatable error, grab the output of `:ls!` before and after the renaming operation.

**Comment by PhilRunninger** [comment] 2018-10-31 18:14
@AnthonyWharton, I just took a peek at your `.vimrc` file. This [chunk of code](https://github.com/AnthonyWharton/dotfiles/blob/master/vim/.vimrc#L151-L170) be wiping out the buffer before NERDTree tries to its `:bwipeout`. Comment out your `autocmd` and see what happens.

**Comment by AnthonyWharton** [comment] 2018-10-31 20:21
Hey @PhilRunninger, Yeah sorry my mistake, it appears something was just cached in an instance of vim that wasn't properly reloaded after I updated.. Seems to be fine now regardless of that little script! Thanks for the quick response 👍

**Closed** 2018-12-06 13:32 UTC
Labels: awaiting feedback
