### ISSUE TITLE
Option to change the default indent size

### ISSUE THREAD

**Issue by zapashcanon** [scrooloose/nerdtree#848] opened 2018-06-03 23:00 UTC
Hi,

I would like to know if there's an option to change (and especially reduce) the size of indent in the tree ? If that's not possible currently, then let's call this a feature request. What I mean by the size of indent is the red thing in this screenshot:

![new document](https://user-images.githubusercontent.com/16472988/40892110-efa6278a-6789-11e8-99d2-3a0aac6910c6.png)

Thanks.

**Comment by PhilRunninger** [comment] 2018-06-04 12:56
There is no such setting in NERDTree. It uses 2 spaces per level, with the root being level 1. The files shown in your screenshot, then should be in column 3.

![image](https://user-images.githubusercontent.com/5598066/40918563-a71c5db8-67d4-11e8-93ad-f8a575d320ef.png)

I suspect the extra spaces are being put in by whatever plugin is supplying the lambda character to NERDTree. Take a look at its options, and let us know what you find.

**Comment by PhilRunninger** [comment] 2018-06-07 14:29
I don't see that as an issue. It's standard practice to put all siblings (files and directories) at the same indentation level. The triangle should **not** be considered part of the directory name. In my screenshot, since `syntax/` and `CHANGELOG` are siblings, they should be at the same indentation, based on the text of their actual names, and in fact, they are. In yours, `src/` and `_oasis` are siblings and they both start in column 3. The only reason your filenames are pushed to the right is, as you discovered, the tags being introduced by [ryanoasis/vim-devicons](https://github.com/ryanoasis/vim-devicons) and [Xuyuanp/nerdtree-git-plugin](https://github.com/Xuyuanp/nerdtree-git-plugin).

This is not a bug, nor something we will be changing, so I'm going to close this issue.

**Closed by PhilRunninger** 2018-06-07 14:29 UTC
Labels: awaiting feedback

**Comment by zapashcanon** [comment] 2018-06-07 14:54
> I don't see that as an issue. It's standard practice to put all siblings (files and directories) at the same indentation level. The triangle should not be considered part of the directory name.

I'm not saying it's an issue. Only that I'd prefer it like this but I understand it's probably not the case for most users.

One thing that could be done would be to add an option `consider triangle as part of the directory name`, set it to `false` as default. If it's set to `yes`, you just have to remove an indent level for files.

I would also completely understand that you don't want to add this as an option. In this case, could you possibly point me to the part of the code that computes the number of indent for files ? I'll just add a local patch to get the behavior I want. :)

> The only reason your filenames are pushed to the right is, as you discovered, the tags being introduced by ryanoasis/vim-devicons and Xuyuanp/nerdtree-git-plugin.

It's only because of nerdtree-git-plugin (I opened an issue there), vim-devicons is fine.

**Comment by PhilRunninger** [comment] 2018-06-07 15:32
Removing this block of code will do what you are requesting: https://github.com/scrooloose/nerdtree/blob/master/lib/nerdtree/tree_file_node.vim#L347-L349. Be aware that your nerdtree will be out of date with the official version.

**Comment by zapashcanon** [comment] 2018-06-07 17:14
Thanks, it works as I wanted. :)

(I just forked the repo, added a commit and I have some script to pull from upstream automatically, should be fine.)

**Comment by roberbnd** [comment] 2018-08-03 14:55
I like the solution of zapashcanon, why wasn't it merged with this project?

**Comment by zapashcanon** [comment] 2018-08-03 15:04
Because the current behavior is the expected one. One that could be done is to add an option that the user has to set and rewrite the code pointed out by @PhilRunninger so it checks for it.

**Comment by roberbnd** [comment] 2018-08-03 15:42
wait it works with the indentation but doesn't open the files, when I am pressing enter (<cr>) or "o" doesn't works.. I tried a global variable g:Indentantion = '' and 
let treeParts = treeParts . g:Indentantion
and it's the same.

**Comment by PhilRunninger** [comment] 2018-08-03 21:22
There are several places in the code that are coupled, and changing one without changing the others is problematic. I'm working on some changes to address a bunch of other issues, and indentation is becoming something I have to deal with. Let's see where that goes before tackling this any further.

**Comment by gbrlsnchs** [comment] 2019-03-27 13:15
> It uses 2 spaces per level, with the root being level 1.

Can this be configurable? Having only a single space in root gets Vim DevIcons unaligned only for root files:
![image](https://user-images.githubusercontent.com/7577128/55078524-1d0a7400-5079-11e9-8f52-9db8b79a9e71.png)
