### ISSUE TITLE
lookupfile can't work on gvim(windows), after changing CWD by NERDtree

### ISSUE THREAD

**Issue by edaplayer** [scrooloose/nerdtree#634] opened 2016-11-03 15:16 UTC
lookupfile can't work on gvim(windows), after changing CWD by NERDtree.

example:
gvim
:e E:\work\project
input cd on nerdtree root directory（E:\work\project）.
click <F5> to open lookupfile

then pop some error:
处理 function <SNR>113_LookupUsing[16]..lookupfile#OpenWindow[19]..genutils#OpenWinNoEa[1]..<SNR>231_ExecWinCmdNoEa 时发生错误:
第   10 行:
E16: 无效的范围: 1sb 4

ps: my vim version is gvim 8.0 (windows 64bit), and no this problem with doing that on ubuntu terminal.
and if I manually changed CWD without changing CWD by NERDtree on gvim(windows) , there is no problem.

Example:
gvim
:cd E:\work\project
click <F5> to open lookupfile

It's fine.

**Comment by lifecrisis** [comment] 2018-09-22 19:36
This is old, so I'm closing.  It seems that the problem is with the other plugin and not with the NERDTree.  The error is being generated by a function from that plugin.  Please report your issue to the author of the "lookupfile" plugin.

**Closed by lifecrisis** 2018-09-22 19:36 UTC
