### ISSUE TITLE
Feature request: open in multiple buffes or windows (tabs) with visual-line mode support

### ISSUE THREAD

**Issue by lewicki-pk** [scrooloose/nerdtree#572] opened 2016-04-21 15:17 UTC
TL;DR:
Can you implement opening multiple files in a new window/tab (with `t`) when user selects them in visual-line mode?

---

First of all - great plugin.
Today when I was using it I came up with a proposal of a new feature:

I wanted to open 3 files with very similar names and I tried to use visual-line mode to select them and than `t` to open them in new tab.

Of course it did not work, but please tell me: is it possible to implement such a feature?

**Comment by PhilRunninger** [comment] 2018-03-15 12:59
@lewicki-pk, This is a duplicate of #49. On that issue is a link to a NERDTree plugin (a gist written by @scrooloose and updated by me) to open the selected files in horizontal splits. It can be modified to open in tabs instead. I'm closing this issue, since there is already a lengthy discussion in #49.

**Closed by PhilRunninger** 2018-03-15 12:59 UTC
