### ISSUE TITLE
How to set up NERDTree to CD to current folder when opening it for the first time via :NERDTree Find

### ISSUE THREAD

**Issue by firedev** [scrooloose/nerdtree#480] opened 2015-09-07 06:27 UTC
Given:

```
$ cd ~/Sites/project
project $ vim
:NERDTreeFind
```

I would like to see NERDTree opening with ~/Sites/project as a root folder. 

Instead I see ~/Sites with project folder selected. I use `:NERDTreeFind` almost exclusively and have to cd to the work folder each time.

**Comment by PickRelated** [comment] 2015-09-12 20:04
I guess for emty buffer you should use :NERDTreeToggle. To combine those functions I wrote a function which determines if file exists and selects function automatically.
```vimscript
function! NERDTreeToggleInCurDir()                                                                                                                                                             
·   " If NERDTree is open in the current buffer
·   if (exists("t:NERDTreeBufName") && bufwinnr(t:NERDTreeBufName) != -1)
·   ·   exe ":NERDTreeClose"
·   else
·   ·   if (expand("%:t") != '')
·   ·   ·   exe ":NERDTreeFind"
·   ·   else
·   ·   ·   exe ":NERDTreeToggle"
·   ·   endif
·   endif
endfunction
```

**Comment by firedev** [comment] 2015-11-04 02:10
Thanks @PickRelated

**Comment by firedev** [comment] 2015-11-19 02:44
Sorry @PickRelated that doesn't work as intended because it closes NERDTree if it's opened instead of doing another search when invoked again from a different file.

**Comment by PickRelated** [comment] 2015-11-19 06:59
@firedev, which is exactly how I wanted it to work. If you need another search - just close it and then open again. Still you can customize this script however you want :)

**Comment by kevindente** [comment] 2016-06-14 22:00
I'm hitting this too. The docs say:

 If no tree exists and the current file is under vim's CWD, then init a
    tree at the CWD and reveal the file. Otherwise init a tree in the current
    file's directory.

Wouldn't this be the "otherwise" case? Is this a bug?

**Comment by PhilRunninger** [comment] 2018-04-10 20:51
Here's perhaps a better explanation of the help text above. Given this tree structure:
```
~/
  pocket/
    wocket/
      zax.txt
  grinch/
    lorax/
      sneetches.txt
```
If you type these commands:
```
$ cd ~/pocket
$ vim wocket/zax.txt
:NERDTreeFind
```
You will see a NERDTree with `~/pocket` as the root folder, and `wocket/zax.txt` revealed. This is the first condition in the help text - `zax.txt` is under CWD, so CWD is used as NERDTree's root.

If instead you type these commands:
```
$ cd ~/pocket
:e ../grinch/lorax/sneetches.txt
:NERDTreeFind
```
NERDTree will open with `~/grinch/lorax` as the root folder and `sneetches.txt` will be revealed. This is the *otherwise* condition in the help text - `sneetches.txt` is not under CWD, so `~/grinch/lorax` (`sneetches.txt`'s directory) is used as NERDTree's root.

If the buffer you're in is not a file on disk, `:NERDTreeFind` will fail with the message `NERDTree: invalid path` or `NERDTree: no file for the current buffer`. This may be new behavior since the creation of this issue, and it's by design. If the file doesn't exist, it can't be found. The best you can do is to use some variation of @PickRelated's function.

**Closed by PhilRunninger** 2018-04-10 20:51 UTC
