### ISSUE TITLE
ClearAllBookmarks does not refresh

### ISSUE THREAD

**Issue by sensorario** [scrooloose/nerdtree#516] opened 2015-11-27 11:11 UTC
After ClearAllBookmarks command, the view is not refreshed and a reload is mandatory to se new tree status ...

**Comment by lifecrisis** [comment] 2017-06-27 00:39
Confirmed this bug on my installation.

**Comment by PhilRunninger** [comment] 2018-05-16 20:47
Not a bug on Mac. I'll check Windows tonight. This bug may have been fixed since last June.

**Comment by PhilRunninger** [comment] 2018-05-18 03:15
This appears to be working correctly now. I'm going to go ahead and close this one.

**Closed by PhilRunninger** 2018-05-18 03:15 UTC
Labels: bug

**Comment by sensorario** [comment] 2018-05-18 10:46
👍
