### ISSUE TITLE
How to choose specific existing window to open a new file in NERDTree

### ISSUE THREAD

**Issue by Nan-Zhang** [scrooloose/nerdtree#461] opened 2015-06-22 22:42 UTC
Hi, there,

Currently I am using NERDTree for helping navigation of vim. But it seems that when I selected a specific file and want to open it, NERDTree always opened it by overwriting the most recent window which is a little annoying sometimes. If there is way to open that file so that we can specify which window should be overwritten?

**Comment by phcerdan** [comment] 2015-10-02 03:09
This would be great

**Comment by PhilRunninger** [comment] 2018-01-02 08:31
Duplicate of #211.

**Closed** 2018-03-14 21:29 UTC
Labels: close?
