### ISSUE TITLE
Buffer Delete breaks NERDTreeToggle

### ISSUE THREAD

**Issue by benlinton** [scrooloose/nerdtree#162] opened 2012-05-09 15:05 UTC
With the NERDTree window open and in focus, I enter the buffer delete (:bd) command.  Then :NERDTreeToggle results in the following error:

```
Error detected while processing function <SNR>15_toggle..<SNR>15_renderView:
E121: Undefined variable: b:NERDTreeRoot
E15: Invalid expression: b:NERDTreeRoot.path.str({'format': 'UI', 'truncateTo': winwidth(0)})
E121: Undefined variable: header
E116: Invalid arguments for function setline
E121: Undefined variable: b:NERDTreeRoot
E15: Invalid expression: b:NERDTreeRoot.renderToString()
```

At this point the only way to fix NERDTreeToggle is to enter the :NERDTree command.
### Additional Details:

Vi IMproved 7.3 (2010 Aug 15, compiled Aug  2 2011 16:49:30)
NerdTree v4.2.0
Using gVim on Windows XP

**Comment by rbong** [comment] 2015-06-01 17:13
The function still fails for me. The issue is that ":NERDTree" still executes with errors and fails. This small fix worked for me:
```vim
nmap <silent> <Leader>t :call g:WorkaroundNERDTreeToggle()<CR>

function! g:WorkaroundNERDTreeToggle()
  try | NERDTreeToggle | catch | silent! NERDTree | endtry
endfunction
```
Note the "silent!"

**Comment by wcamarao** [comment] 2015-06-02 13:41
Thanks for the update @rbong, the one I posted before used to work, but since I updated NERDTree to current master a few days ago, it stopped working and I haven't had the chance to look into it. Thanks for sharing, I'll give it a try.

**Comment by wcamarao** [comment] 2015-06-03 18:18
Just verified the silent! before the NERDTree call kept the workaround valid for the current NERDTree stable.

**Comment by squarism** [comment] 2015-07-01 21:46
This fix/thread is fantastic.  Saving my sanity.

**Comment by bl4ckn0de** [comment] 2015-10-15 15:03
problem silenced in my workstation, Ubuntu 14.04

**Comment by Rican7** [comment] 2016-07-14 16:17
I'm still having issues even with the `g:WorkaroundNERDTreeToggle` function.

The "errors" (status-line execution errors) are no longer being thrown, but the behavior of NERDTree opening is still off, as it causes a strange issue where my current buffer is opened in just a NERDTree size split window.

Regardless, the `g:WorkaroundNERDTreeToggle` function is a hacky workaround... the plugin should really be detecting the condition where the buffer no longer exists, and then handle that appropriately (fall-back to a reopening?).

**Comment by Rican7** [comment] 2016-07-14 16:19
Hmm, actually this seems to be fixed by 0544ff524c5209cf885984739dde941fd9fd37af, which was a fix for #375.

Should this be closed @scrooloose? Maybe a patch release (`5.0.1`?) for the bugfix?

**Comment by Rican7** [comment] 2016-07-14 16:31
_Actually_, I'm still getting weird behavior, even after upgrading to the newest master:

![vim-nerdtree-toggle-bug](https://cloud.githubusercontent.com/assets/742384/16847396/e3b22d60-49be-11e6-8ed1-1dd77dd41093.gif)

😞

**Comment by PhilRunninger** [comment] 2017-01-03 19:49
This issue seems to have been fixed, as mentioned above. Closing....

**Comment by whiteShtef** [comment] 2017-11-01 18:18
Im still experiencing this issue as of commit f554c20.

**Comment by lifecrisis** [comment] 2017-11-01 21:12
I know what's causing this. The `:RemoveHiddenBuffers` command must be running the `:bwipeout` command instead of the `:bdelete` command.

@whiteShtef, is this your issue as well (i.e., is a call to `:bwipeout` the root of your problem)?  Also, @Rican7, can you confirm that `:bwipeout` was the original cause of the bug you reported? 

If we can confirm this, I'll reopen.

**Comment by Rican7** [comment] 2017-11-02 01:38
> I know what's causing this. The `:RemoveHiddenBuffers` command must be running the `:bwipeout` command instead of the `:bdelete` command.

That's precisely what's happening: https://github.com/Rican7/dotfiles/blob/7ecd8991ff650ae3fca506820269a0d52874c226/config-rc/.vimrc#L265

**Comment by whiteShtef** [comment] 2017-11-02 08:11
Is there a simple fix to this?

**Comment by lifecrisis** [comment] 2017-11-02 12:12
@whiteShtef The simple fix is to just use `:bdelete` in the NERDTree buffer for now. I realize that's not a long term solution, but it works for the moment.

I've diagnosed the problem, and it will likely be the next bug that I tackle.  It's somewhat tricky, but a fix is definitely feasible soon.

@Rican7 Thanks for getting back to me.

**Comment by PhilRunninger** [comment] 2018-04-27 12:17
I believe this was fixed by #814. @Rican7 and @whiteShtef, can you verify that for me?

**Comment by whiteShtef** [comment] 2018-04-27 18:03
Now I'm getting
```
Error detected while processing function 200[2]..201:
line    5:
E121: Undefined variable: b:NERDTree
line    7:
E121: Undefined variable: b:NERDTree
```
😕 Am I missing something?

**Comment by PhilRunninger** [comment] 2018-04-27 20:47
I'll need more information to know for sure. Can you share your `vimrc` file? And to be sure we're talking about the same problem, describe how you reproduce these errors.

**Comment by whiteShtef** [comment] 2018-04-27 20:52
The relevant part of my `vimrc`:

```
"NERDTree config
autocmd vimenter * NERDTree " open on start
autocmd BufWinEnter * NERDTreeMirror " open in every new tab
autocmd BufWinEnter * wincmd p " when opened in new tab, switch to FILE buffer (default is the NERDTree buffer)“
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif " autoclose window/tab if last buffer is nerdtree
map <C-n> :NERDTreeToggle<CR>
```

The last line bounds NERDTreeToggle to C-n. I get the error when toggling the previously closed (toggled) NERDTree buffer.

**Comment by PhilRunninger** [comment] 2018-04-30 13:28
@whiteShtef, I can't reproduce your errors with the snippet you provided. Can you share all of your vimrc? Remove any confidential information, of course. There are lots of options that could be affecting NERDTree's behavior.

**Comment by PhilRunninger** [comment] 2018-08-07 16:04
@whiteShtef , I just took a closer, more careful look at your issue (sorry it took so long). I'd failed to see your last sentence, and indeed, I **can** recreate your issue now. Anyway, I think I figured out what's causing the error, but not necessarily why. If you change your `autocmd`s from `BufWinEnter` to `TabNew`, the problem will go away. It's not necessary to mirror your NERDTree when opening a file in a new window (a split on the current tab), because that tab already has a NERDTree. Only when you create a new tab will you need to mirror the NERDTree.

If this solves your issue, go ahead and close this issue again.

**Comment by whiteShtef** [comment] 2018-08-07 16:11
Correct. Works like a charm.

**Comment by PhilRunninger** [comment] 2018-08-08 02:45
No problem. I got you covered.

**Closed** 2018-08-08 02:45 UTC
Labels: bug
