### ISSUE TITLE
macOS Terminal.app ^G

### ISSUE THREAD

**Issue by vitkabele** [scrooloose/nerdtree#959] opened 2019-02-26 20:52 UTC
### Environment

* Operating System: macOS 10.14.3
* Vim version `:version`: 
      VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Aug 17 2018 17:24:51)
      Included patches: 1-503, 505-680, 682-1283
      Compiled by root@apple.com
      Normal version without GUI.
* NERDTree version `git rev-parse --short HEAD`:  84737f2
* NERDTree settings applied in your vimrc, if any:
    ```vim
    ```

### Process

1. Just install the plugin and open NERDTree. Clean instalation, no complicated .vimrc setup

### Current Result

Before each entry in NERDTree is displayed `^G` sequence

### Expected Result

I guess that this sequence shouldn't be there :)

### Screenshot(s)
![screenshot 2019-02-26 at 21 48 12](https://user-images.githubusercontent.com/13497216/53445222-5adf9280-3a10-11e9-987d-50be9e37444e.png)

### Possible Fix

I fixed this by putting `let g:NERDTreeNodeDelimiter = "\u00a0"` into my `~/.vimrc` as mentioned by someone [here](https://stackoverflow.com/questions/53657545/nerdtree-g-before-folder-and-file-names-osx-terminal-vim). I guess that it should not be problem to set the sequence as default delimiter and the problem will be fixed.

**Comment by CharlesB2** [comment] 2019-02-26 21:15
Duplicate of #928 ?

**Comment by vitkabele** [comment] 2019-03-03 22:58
Sorry, my bad. I didn't notice this one.

**Comment by PhilRunninger** [comment] 2019-03-04 15:49
@vitkabele , if you wouldn't mind, I have a new PR out that could use some testing. You can just do
```
git pull
git checkout smarter_delimiter_default
git pull
```
on the NERDTree repo to give it a go. All my vims have the conceal feature, so I can't give it a complete test.

Thanks!

**Comment by PhilRunninger** [comment] 2019-03-07 13:26
Fixed by #963.

**Closed by PhilRunninger** 2019-03-07 13:26 UTC
