### ISSUE TITLE
[nvim] partial cursorline for rendered file node

### ISSUE THREAD

**Issue by gloomy-ghost** [scrooloose/nerdtree#960] opened 2019-03-02 23:44 UTC
### Environment

* Operating System: debian buster
* Vim version: nvim v0.3.4
* NERDTree version: 84737f2 

### Process
1. Open a directory using nvim and toggle nerdtree
2. `:set cursorline`

### Current Result
cursorline is drawn partially for file nodes. directory nodes are fine though.
![default](https://user-images.githubusercontent.com/13086421/53689024-97651280-3db1-11e9-9a43-e42be5d38467.png)
![default](https://user-images.githubusercontent.com/13086421/53689025-9e8c2080-3db1-11e9-94ea-3dc448372d6a.png)

### Expected Result
cursorline should be drawn fully.
![default](https://user-images.githubusercontent.com/13086421/53689040-d4c9a000-3db1-11e9-8ec6-e4ff8aafe4c6.png)(screenshot in vim)

**Comment by PhilRunninger** [comment] 2019-03-04 05:57
Duplicate of #953. This is a reported bug in neovim.

**Closed by PhilRunninger** 2019-03-04 05:57 UTC
