### ISSUE TITLE
Directory Coloring in NerdTree

### ISSUE THREAD

**Issue by go4zeeshan** [scrooloose/nerdtree#334] opened 2014-04-27 11:39 UTC
I am trying to run the commands in the following manner:
1. I place the command hi Directory guifg=#96CBFE guibg=#00ff00 in my .vimrc file
2. Then I place the command hi link Directory Keyword in my badwolf.vim color scheme file

But when I restart VIM the NerdTree shows all white color.

I also tried running the command :hi Directory guifg=#FF0000 ctermfg=red in VIM but no success

**Comment by PhilRunninger** [comment] 2017-12-30 08:48
@go4zeeshan , I've been going through the backlog of issues. I cannot reproduce this issue. Can you provide more information about this, or close the issue?

**Closed** 2018-03-14 21:32 UTC
Labels: awaiting feedback, close?
