### ISSUE TITLE
NERDTree is not retaining the open tree and collapsed tree between the show and hide toggling of NerdTree

### ISSUE THREAD

**Issue by nepsdotin** [scrooloose/nerdtree#708] opened 2017-06-15 07:17 UTC
_To assist in resolving your issue, provide as much information as possible, in place of the ellipses (`…`) below._

---
**Environment:** _Describe your Vim/NERDTree setup._

>* Operating System: … Mac, Linux ubuntu
>* Vim version `:version`:Vi IMproved 8.0
>* NERDTree version `git rev-parse --short HEAD`:b0bb781
>* NERDTree settings applied in your vimrc, if any: F2 For show and hide of Nerdtree
>
>   ```
>   …
>   ```

**Process:** _List the steps that will recreate the issue._

>1. 
Assume i expand the directory tree present some of them. Now I press F2 which hides NERDTree now when i press again F2 NerdTree shows up but the Expansion of the tree is not retained between Show and Hide of NerdTree. its really painful to expand all the open dir tree and navigate everytime i hide NerdTree window and come back again.

**Comment by lifecrisis** [comment] 2017-06-15 12:00
Please include your `<F2>` mapping.  That's the only way for us to see the commands that are actually being executed.

**Comment by juanibiapina** [comment] 2017-09-27 19:09
F2 is probably mapped to NERDTree, not toggle. This is a default that doesn't help much.

**Comment by lifecrisis** [comment] 2017-09-27 23:04
Thanks, @juanibiapina. You are likely correct here.

**Comment by mboughaba** [comment] 2017-11-08 18:51
I tried reproducing this below are my findings.


1 . First using the toggle command
The problem cannot be reproduced using **NERDTreeToggle**, the expanded folder structure will be preserved.
2. Second using NERDTree command
    If we hide nerd tree using the toggle command (or NERDTreeClose) then reopen it using **NERDTree** command **the expanded folder structure won't be preserved**.

To me this is normal behavior.
According to the help:

> :NERDTree [<start-directory> | <bookmark>]                         *:NERDTree*
    Opens a fresh NERD tree. The root of the tree depends on the argument
    given. There are 3 cases: If no argument is given, the current directory
    will be used.  If a directory is given, that will be used.

>:NERDTreeToggle [<start-directory> | <bookmark>]             *:NERDTreeToggle*
    If a NERD tree already exists for this tab, it is reopened and rendered
    again.  If no NERD tree exists for this tab then this command acts the
    same as the |:NERDTree| command.

**Comment by lifecrisis** [comment] 2018-05-01 17:08
This issue looks like it has been solved.  Now closing... reopen if necessary.

**Closed by lifecrisis** 2018-05-01 17:08 UTC
Labels: awaiting feedback
