### ISSUE TITLE
NERDTreeToggle causes error when on other windows are open

### ISSUE THREAD

**Issue by AmaruCoder** [scrooloose/nerdtree#514] opened 2015-11-25 21:45 UTC
If there is only one window with NERDTree open, the command `NERDTreeToggle` produces the error below:

![NERDTree error](https://photos-5.dropbox.com/t/2/AACx6U0U_wqEFkQ6FbsoV2135WXwLzyiA2xGHaycyDxPgQ/12/301329/png/32x32/3/1515049200/0/2/NERDTree-1.png/EIuaNxjO7fDqAyACKAI/lTTHVZ3tfdWMaz2cl8CaJZv2MTAu27_OwaUMvMMc2XA?dl=0&preserve_transparency=1&size=2048x1536&size_mode=3)

**Comment by martinbeentjes** [comment] 2015-12-14 08:38
I got a similar error about trailing characters. I removed the nerdtree directory in `~/.vim/bundle` (`rm -r ~/.vim/bundle/nerdtree`) and executed the following two commands:

 ```
cd ~/.vim/bundle
git clone https://github.com/scrooloose/nerdtree.git
```

This solved the issue for me.

**Comment by AmaruCoder** [comment] 2015-12-15 06:31
martinbenntjes, thank you for the suggestion. I tried it, but I still get the error message.

**Comment by PhilRunninger** [comment] 2018-01-02 08:35
@AmaruCoder, the link to your error is broken. Can you update the issue with new information, or close it?

**Comment by AmaruCoder** [comment] 2018-01-04 02:27
I have updated the link to the error screen capture. Thank you.

**Comment by martinbeentjes** [comment] 2018-01-04 10:09
The screen capture is still broken here.

**Comment by PhilRunninger** [comment] 2018-01-04 14:11
This can be reproduced with the following steps:
```
$ vim
:NERDTreeToggle
<C-W>o
:NERDTreeToggle
```
I would call this an edge case, as `NERDTreeToggle` and `NERDTreeClose` are intended to close the NERDTree window, leaving the remaining window(s) open. Perhaps a cleaner error message is in order, but the effect will be the same: stop the close from happening.

@martinbeentjes, the screenshot shows vim error messages that read:
```
Error detected while processing function 194..195..204:
line 18:
E444: Cannot close last window
Press ENTER or type command to continue
```

**Closed** 2018-03-14 21:13 UTC
Labels: close?

**Comment by AmaruCoder** [comment] 2018-03-15 01:17
Thank you for following up on this issue. And for writing such an awesome plugin.
