### ISSUE TITLE
Trying to recover a blank file replaces the buffer with NERDTree

### ISSUE THREAD

**Issue by Forethinker** [scrooloose/nerdtree#245] opened 2013-03-15 17:55 UTC
`vim -r ""`
Trying to open a 'No Name' file in vim results in
"Error detected while processing function nertree#checkForBrowse...215..216:"
The recovered file is opened momentarily and then NERDTree opens right away, replacing the buffer.
I observed this behavior even when I cleared out my .vimrc. So I do not think this is a configuration issue. The only way I got around this behavior was by setting `-u NONE` flag when opening the vim to avoid loading the plugin.
Also Changing `NERDTreeChDirMode` did not do anything to resolve this issue. How could I suppress this behavior so that I could edit my recovered file?

**Comment by PhilRunninger** [comment] 2017-12-26 03:53
@Forethinker , Is this still happening? A lot has changed to NERDTree since you reported this. I'm going to close this, as I cannot reproduce it. Reopen if necessary.

**Closed by PhilRunninger** 2017-12-26 03:53 UTC
