### ISSUE TITLE
"Key not present in Dictionary" when executing CD command

### ISSUE THREAD

**Issue by lostscrew** [scrooloose/nerdtree#392] opened 2014-11-02 12:20 UTC
I get the following error, although the command still seems to work:

```
Error detected while processing function nerdtree#ui_glue#invokeKeyMap..71..70..nerdtree#ui_glue#chRootCwd:
line    7:
E716: Key not present in Dictionary: path.str()
E15: Invalid expression: cwd.str() == g:NERDTreeFileNode.GetRootForTab().path.str()
```

I am using the Cygwin version of Vim:

```
$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun 22 2014 14:31:17)
Included patches: 1-335
Compiled by <cygwin@cygwin.com>
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   +perl/dyn        +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python/dyn      +viminfo
+cscope          +lispindent      +python3/dyn     +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      +lua/dyn         +rightleft       +windows
+diff            +menu            +ruby/dyn        +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/etc"
 f-b for $VIMRUNTIME: "/usr/share/vim/vim74"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -I/usr/include/ncursesw  -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/usr/src/ports/vim/vim-7.4.335-1.x86_64/build=/usr/src/debug/vim-7.4.335-1 -fdebug-prefix-map=/usr/src/ports/vim/vim-7.4.335-1.x86_64/src/vim74=/usr/src/debug/vim-7.4.335-1 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L.   -L/usr/local/lib -Wl,--as-needed -o vim.exe        -lm -lelf    -lncursesw -liconv -lintl   -Wl,--enable-auto-import -Wl,--export-all-symbols -Wl,--enable-auto-image-base -fstack-protector  -L/usr/lib/perl5/5.14/x86_64-cygwin-threads/CORE -lperl -ldl -lcrypt
```

**Comment by mikedfunk** [comment] 2015-05-06 18:52
same error here

**Comment by scrooloose** [comment] 2015-05-06 18:58
@mikedfunk are you also using cygwin? if so, are you able to reproduce this in gvim for windows? I'm guessing this is issue is only occurring in cygwin but want to be sure. Can you give me exact steps to reproduce it?

**Comment by mikedfunk** [comment] 2015-05-06 19:03
No, I am on mac. I get this when I call `:NERDTreeFind` occasionally. I'm thinking it might have to do with  changes to the contents of the directory that contains the file I'm on when calling this command.

**Comment by erlandsona** [comment] 2015-08-24 01:37
Any updates on this one? I'm getting the same error.

I try to CD after cding into a specified directory and...
```
Error detected while processing function nerdtree#ui_glue#invokeKeyMap..72..71..nerdtree#ui_glue#chRootCwd:
line    7:
E716: Key not present in Dictionary: path.str()
E15: Invalid expression: cwd.str() == g:NERDTreeFileNode.GetRootForTab().path.str()
```

A bit more info...
I'm using dhruvasagar's fork of tpopes/vim-vinegar to make nerdtree behave like a split explorer vs a project drawer for more vim-like workflow. Tried vifm but vim integration was awkward and netrw keeps randomly setting files to nomodifiable or whatever. 

Point is I moved away from nerdtree because it made manipulating the FS too slow compared to using like finder. But that's super annoying going back an forth so I tried netrw and same story there, the ncurses program vifm showed real promise until I tried integrating it with actual vim. Switching between vim and vifm isn't ideal. So I'm back to nerdtree and deciding to use as a split explorer. Hopefully this provides a nice blend of all the worlds.

**Comment by juliogc** [comment] 2016-02-16 15:44
Anyone solved this problem? I'm having a similar issue here when I try to use CD after cd.

OS: Ubuntu 14.04

``` bash
$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:32)
Included patches: 1-52
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by buildd@
```

Error:
``` Bash
Error detected while processing function nerdtree#ui_glue#invokeKeyMap..75..74..nerdtree#ui_glue#chRootCwd:                                                                             
line    7:
E716: Key not present in Dictionary: path.str()
E15: Invalid expression: cwd.str() == g:NERDTreeFileNode.GetRootForTab().path.str()
Press ENTER or type command to continue
```

**Comment by erlandsona** [comment] 2017-02-03 17:56
Any updates on this? I'm still getting it in Vim8.

**Comment by alexbyk** [comment] 2017-02-11 11:07
I'm getting this error after deleting files in neovim

**Comment by PhilRunninger** [comment] 2018-05-02 17:04
I cannot reproduce this error given the scenarios presented above. If someone could show the steps needed to produce a repeatable error, that would help greatly.

**Comment by erlandsona** [comment] 2018-05-02 20:55
Seems like the code at
https://github.com/scrooloose/nerdtree/blob/183bb53485f32f3be5e920cedc657dfc9c6d7eda/lib/nerdtree/tree_file_node.vim#L10
And
https://github.com/scrooloose/nerdtree/blob/68313ef0f512897d63aef55909847759123ce918/autoload/nerdtree/ui_glue.vim#L153

Are relevant?
My error is saying that `path.str()` is not present in the `g:NERDTreeFileNode` dictionary.

**Comment by PhilRunninger** [comment] 2018-05-03 14:12
That is the code I'm looking at too, but I need to know what conditions cause the error. As I said, this issue is not happening for me.

**Comment by lifecrisis** [comment] 2018-06-13 13:02
**ATTENTION:** We need **exact** steps to reproduce this error in order to fix it.  We need the version if Vim you're using, the system you're running, and an example directory hierarchy to work with.  Anything else is just wasting time.

**Comment by erlandsona** [comment] 2018-06-13 14:45
@lifecrisis I've had this issue in all versions of vim I've tried since posting.
That apparently includes Vim7,8 and NeoVim.
I'm on OSX Sierra & High Sierra.
Example Directory Hierarchy might be:
```
folderA/
  .keep
folderB/
  .keep
```
Open NerdTree and `CD` between the directories and the error should appear.

Here's my existing config
```
Plug 'scrooloose/nerdtree' ", { 'on': 'NERDTreeToggle' }
Plug 'dhruvasagar/vim-vinegar', { 'as': 'nerd-vinegar' }

let NERDTreeChDirMode = 0 " Don't change Vim's CWD
let NERDTreeHijackNetrw = 1
let NERDTreeHighlightCursorline = 1
let NERDTreeIgnore = ['DS_Store']
let NERDTreeMouseMode = 3 " Single click any node to open.
let NERDTreeShowHidden = 1
let NERDTreeShowLineNumbers = 1
let NERDTreeCascadeOpenSingleChildDir = 0
let NERDTreeAutoDeleteBuffer = 1
```

**Comment by lifecrisis** [comment] 2018-06-13 15:42
I can't reproduce this anywhere.  We'll leave this open until someone can provide well-defined context for this bug.

**Comment by lifecrisis** [comment] 2018-09-22 20:05
No one has given any useful feedback or provided the **precise** steps that we need to reproduce this issue.  I'll close this.  If your problem persists, please open a new issue with exact instructions to reproduce the bug.

**Closed by lifecrisis** 2018-09-22 20:05 UTC
